# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heart_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('record_id', models.IntegerField(default=0)),
                ('heart_time', models.CharField(max_length=200)),
                ('heart_date', models.CharField(max_length=200)),
                ('heart_rate', models.CharField(max_length=200)),
                ('average_rate', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_heart_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(default='', max_length=200)),
                ('end_time', models.CharField(default='', max_length=200)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_shake_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('shake_x_data', models.TextField(null=True)),
                ('shake_x_detail_data', models.TextField(null=True)),
                ('shake_y_data', models.TextField(null=True)),
                ('shake_y_detail_data', models.TextField(null=True)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='record_up_shake_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('shake_x_data', models.TextField(null=True)),
                ('shake_x_detail_data', models.TextField(null=True)),
                ('shake_y_data', models.TextField(null=True)),
                ('shake_y_detail_data', models.TextField(null=True)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shake_all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(default='', max_length=200)),
                ('record_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(default='', max_length=200)),
                ('end_time', models.CharField(default='', max_length=200)),
                ('beside_x_data', models.TextField(null=True)),
                ('beside_x_pos', models.TextField(null=True)),
                ('beside_y_data', models.TextField(null=True)),
                ('beside_y_pos', models.TextField(null=True)),
                ('up_x_data', models.TextField(null=True)),
                ('up_x_pos', models.TextField(null=True)),
                ('up_y_data', models.TextField(null=True)),
                ('up_y_pos', models.TextField(null=True)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shake_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=0)),
                ('record_id', models.IntegerField(default=0)),
                ('shake_date', models.CharField(max_length=200)),
                ('shake_time', models.CharField(default='', max_length=200)),
                ('x_data', models.TextField(null=True)),
                ('y_data', models.TextField(null=True)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField()),
                ('grade_date', models.CharField(max_length=200)),
                ('grade_time', models.CharField(max_length=200)),
                ('grade_detail_time', models.CharField(default='', max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('rapid_time', models.CharField(max_length=200)),
                ('x_pos', models.CharField(max_length=200)),
                ('y_pos', models.CharField(max_length=200)),
                ('x_shake', models.FloatField(null=True)),
                ('y_shake', models.FloatField(null=True)),
                ('heart_rate', models.IntegerField(null=True)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('item_info', models.TextField(null=True)),
                ('item_rule', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoot_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_date', models.CharField(max_length=200)),
                ('shoot_time', models.CharField(default='', max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('x_shake_data', models.TextField(null=True)),
                ('y_shake_data', models.TextField(null=True)),
                ('x_shake_pos', models.TextField(null=True)),
                ('y_shake_pos', models.TextField(null=True)),
                ('x_up_shake_data', models.TextField(null=True)),
                ('y_up_shake_data', models.TextField(null=True)),
                ('x_up_shake_pos', models.TextField(null=True)),
                ('y_up_shake_pos', models.TextField(null=True)),
                ('is_process', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=100)),
                ('intro', models.TextField(null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
