# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot_report',
            name='total_grade',
            field=models.FloatField(null=True),
        ),
    ]
