# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shootweb', '0002_shoot_report_total_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_model_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('model_path', models.CharField(default='', max_length=500)),
                ('build_time', models.CharField(default='', max_length=200)),
                ('model_type', models.IntegerField(default=0)),
                ('model_info', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
            ],
        ),
    ]
