# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_bit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date_score', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='image_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('img_type', models.IntegerField(default=0)),
                ('img_label', models.CharField(default='', max_length=100)),
                ('remark', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='faceinfo',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faceinfo',
            name='filename',
            field=models.TextField(),
        ),
    ]
