# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_bit', '0004_user_info_faceset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_info',
            name='face_token',
            field=models.TextField(default=''),
        ),
    ]
