# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_bit', '0007_user_info_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_info',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
