# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_bit', '0008_game_info_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_info',
            name='img_url',
            field=models.TextField(default=''),
        ),
    ]
